version: 2

references:

  install: &install
    run:
      name: Install dependencies and apistrap on Archlinux
      command: |
        set -x
        pip install --user coveralls "coverage<5.0"
        pip install --user .

  test: &test
    run:
      name: Run tests.
      command: |
        python setup.py test

  deploy: &deploy
    run:
      name: PyPI deploy
      command: |
        pip install wheel setuptools --upgrade --user
        bash <(curl -fsSL https://raw.githubusercontent.com/iterait/ci-utils/master/pypi_deploy.sh)

  coverage: &coverage
    run:
      name: Report test coverage
      command: |
        coverage run --source=apistrap setup.py test
        coverage report
        COVERALLS_REPO_TOKEN=QEAuo5Pufwd8TGqQiqt7a1HWWp3i9mL0Y coveralls

  test_job: &test_job
    working_directory: ~/apistrap
    steps:
      - checkout
      - *install
      - *test


jobs:

  test_py_38:
    <<: *test_job
    docker:
      - image: circleci/python:3.8

  test_py_39:
    <<: *test_job
    docker:
      - image: circleci/python:3.9

  coverage:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/apistrap
    steps:
      - checkout
      - *install
      - *coverage

  deploy:
     docker:
       - image: iterait/archlinux-dev
     working_directory: ~/apistrap
     steps:
       - checkout
       - *install
       - *deploy

workflows:
  version: 2
  test-doc-deploy:
    jobs:
      - test_py_38
      - test_py_39
      - coverage:
          requires:
            - test_py_38
            - test_py_39
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test_py_38
            - test_py_39
            - coverage

  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - dev
    jobs:
      - test_py_38
      - test_py_39
