version: 2

references:

  install: &install
    run:
      name: Install dependencies and apistrap on Archlinux
      command: |
        set -x
        pip install coveralls coverage
        pip install -e .

  test: &test
    run:
      name: Run tests.
      command: |
        python setup.py test

  deploy: &deploy
    run:
      name: PyPI deploy
      command: |
        pip3 install wheel setuptools --upgrade
        bash <(curl -fsSL https://raw.githubusercontent.com/iterait/ci-utils/master/pypi_deploy.sh)

  coverage: &coverage
    run:
      name: Report test coverage
      command: |
        coverage run setup.py test
        coverage report
        COVERALLS_REPO_TOKEN=QEAuo5Pufwd8TGqQiqt7a1HWWp3i9mL0Y coveralls

jobs:

  test_archlinux:
    docker:
      - image: iterait/archlinux
    working_directory: ~/apistrap
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.11.0-ce
      - checkout
      - *install
      - *test

  coverage:
    docker:
      - image: iterait/archlinux
    working_directory: ~/apistrap
    steps:
      - checkout
      - *install
      - *coverage

  deploy:
     docker:
       - image: iterait/archlinux
     working_directory: ~/apistrap
     steps:
       - checkout
       - *install
       - *deploy

workflows:
  version: 2
  test-doc-deploy:
    jobs:
      - test_archlinux
      - coverage:
          requires:
            - test_archlinux
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test_archlinux
            - coverage

  nightly-build:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - dev
    jobs:
      - test_archlinux
